version: '3.8'

services:
  devsecops-orchestrator:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: devsecops_orchestrator_container
    
    environment:
      PYTHONUNBUFFERED: 1
      JIRA_API_KEY: ${JIRA_API_KEY} 
    
   
    ports:
      - "8000:8000"
      
    networks:
      - acip_project_network

networks:
  acip_project_network:
    driver: bridge